# -*- coding: utf-8 -*-
"""calculadora-vigas-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgQCZHEm-Ntbgv3GMVcaFg6DwxnJ49rf
"""

#importando...
import os
import sys

#criando função para limpar a tela e exibir apenas o resultado.
def limpar_tela():
  # Verifica se o código está rodando no Google Colab ou Jupyter Notebook
  if 'ipykernel' in sys.modules or 'google.colab' in sys.modules:
        from IPython.display import clear_output
        clear_output()
  else:
        # Se não estiver no Colab, roda no terminal comum (Windows, Mac ou Linux)
        os.system('cls' if os.name == 'nt' else 'clear')

#Iniciando o projeto
print('=+'*10)
print('PROJETO 01')
print('=+'*10)

#Inserindo dados
nome = input('Qual o nome da viga? ')
v1 = float(input('Qual o vão da viga em metros? ').replace(',','.'))
q1 = float(input('Qual é a carga distribuida que atua sobre ela em kN/m? ').replace(',','.'))
q1c = q1*101.97
mm = (q1*v1**2)/8

#Regras
if mm<50:
  status = 'APROVADA: Viga com carga leve.'
elif mm<=150:
  status = 'ATENÇÃO: Viga com carga moderada. Verifique o detalhamento da armadura'
else:
  status = 'REPROVADA: Carga excessiva! Necessário redimensionar a seção da viga.'

# Chamando comando para limpar a tela
limpar_tela()

print('--- RELATÓRIO ESTRUTURAL ---')
print(f'Viga Analisada: {nome} \nVão da Viga: {v1:.2f}m \nCarga Original: {q1:.2f}kN/m \nCarga Convertida: {q1c:.2f}kgf/m \nMomento Fletor Máximo: {mm:.2f}kN.m \nStatus: {status}')
print('')
input('Pressione ENTER para sair...')